# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-20 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('menus', '0002_auto_20160818_2336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Represents the price for the item.', max_digits=6)),
                ('chef', models.ForeignKey(help_text='Foreign key to the chef making the meal.', on_delete=django.db.models.deletion.CASCADE, to='chefs.Chef')),
                ('customer', models.ForeignKey(help_text='Foreign key to the user who made the order.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_address', models.ForeignKey(help_text='Foreign key to the address information of the customer.', on_delete=django.db.models.deletion.CASCADE, to='billing.Address')),
                ('item', models.ManyToManyField(help_text='Foreign key to the selected items.', to='menus.Item')),
            ],
        ),
    ]
