# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Represents the price for the item.', max_digits=6, null=True),
        ),
    ]
