# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Represents specified name the address.', max_length=20, null=True)),
                ('street_address', models.CharField(help_text='Representsthe street address.', max_length=50)),
                ('city', models.CharField(help_text='Represents specified city.', max_length=30)),
                ('state', models.CharField(help_text='Represents specified state.', max_length=2)),
                ('zip', models.CharField(help_text='Represents specified zip code.', max_length=5)),
                ('instructions', models.CharField(blank=True, help_text=' Represents special instructions for pickup or delivery.', max_length=200, null=True)),
                ('chef', models.ForeignKey(blank=True, help_text='Foreign key to the chef that saved the address.', null=True, on_delete=django.db.models.deletion.CASCADE, to='chefs.Chef')),
                ('user', models.ForeignKey(blank=True, help_text='Foreign key to the user that saved the address.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
