# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 00:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefInfo',
            fields=[
                ('user_info', models.OneToOneField(help_text='Connects userto the ChefInfo class.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('star_rating', models.IntegerField(default=0, help_text='average value ofstar ratings')),
            ],
        ),
    ]
