# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chefs', '0001_initial'),
        ('patrons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text="Patron's review of a chef/meal.", max_length=500, null=True)),
                ('stars', models.IntegerField(help_text="Patron's star rating for a meal")),
                ('chef', models.ForeignKey(help_text='Foreign key to the chef that the review is about', on_delete=django.db.models.deletion.CASCADE, to='chefs.Chef')),
                ('patron', models.ForeignKey(help_text='Foreign key to the patron the review is from.', on_delete=django.db.models.deletion.CASCADE, to='patrons.Patron')),
            ],
        ),
    ]
