# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 02:25
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronInfo',
            fields=[
                ('user_info', annoying.fields.AutoOneToOneField(help_text='The instance of the userclass that corresponds to this patron', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
