# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 00:33
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroninfo',
            name='user_info',
            field=annoying.fields.AutoOneToOneField(help_text='Automatically connects userto the PatronInfo class when a useris created', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
