# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(help_text='Foreign key to the menu the item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menus.Menu'),
        ),
    ]
